package net.runelite.client.plugins.microbot.actionrecorder.model;

public enum ActionRecordType
{
	SESSION_START,
	SESSION_END,
	OPERATOR_MARKER,
	INTERACTION,
	GAME_TICK,
	CONTAINER_CHANGE,
	ANIMATION_CHANGE,
	GRAPHIC_CHANGE,
	WIDGET_LOADED,
	WIDGET_CLOSED,
	VARBIT_CHANGE,
	STAT_CHANGE,
	CHAT_MESSAGE,
	GAME_STATE_CHANGE,
	GAME_OBJECT_CHANGE,
	GROUND_ITEM_CHANGE
}
