package net.runelite.client.plugins.microbot.actionrecorder.model;

public enum ActionRecordType
{
	SESSION_START,
	SESSION_END,
	OPERATOR_MARKER,
	INTERACTION,
	WALK_DESTINATION,
	GAME_TICK,
	CONTAINER_CHANGE,
	ANIMATION_CHANGE,
	GRAPHIC_CHANGE,
	WIDGET_LOADED,
	WIDGET_CLOSED,
	VARBIT_CHANGE,
	STAT_CHANGE,
	CHAT_MESSAGE,
	GAME_STATE_CHANGE,
	GAME_OBJECT_CHANGE,
	OBJECT_TARGET_STATE,
	GROUND_ITEM_CHANGE,
	KEYBOARD_INPUT,
	CAMERA_CHANGE
}
