name: Manually Sync Upstream → Fork (main & development)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'  # Daily at 8AM AEST

jobs:
  sync-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote add upstream https://github.com/chsami/Microbot.git
          git fetch upstream

      - run: |
          git checkout -B main origin/main
          git merge --ff-only upstream/main || echo "✅ main already up to date"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/JogOnJohn/Microbot.git main

  sync-development:
    needs: sync-main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote add upstream https://github.com/chsami/Microbot.git
          git fetch upstream

      - run: |
          git checkout -B development origin/development
          git merge --ff-only upstream/development || echo "✅ development already up to date"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/JogOnJohn/Microbot.git development
